### ISSUE TITLE
ImportError: cannot import name 'MutableSequence' from 'collections'

### ISSUE THREAD

**Issue by Winter-Sno** [CPJKU/madmom#535]
### Expected behaviour

I want to do onset detection in a classical music piece.
I expect the program to return an arraylist like [1,2,3,4,...] marking the onset timestamp of each note.

### Actual behaviour

The program did nothing and an error like this occurred. (╥﹏╥...)
```
Traceback (most recent call last):
  File "D:\workspace\SRT_simulation\madmom_note_extract.py", line 1, in <module>
    import madmom
  File "D:\anaconda3\Lib\site-packages\madmom\__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "D:\anaconda3\Lib\site-packages\madmom\audio\__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "madmom\\audio\\comb_filters.pyx", line 15, in init madmom.audio.comb_filters
  File "D:\anaconda3\Lib\site-packages\madmom\processors.py", line 23, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (D:\anaconda3\Lib\collections\__init__.py)
```

### Steps needed to reproduce the behaviour

```python
import madmom

filename = '01.Overture.flac'


def madmom_get_note_map(filename):
    proc = madmom.features.onsets.CNNOnsetProcessor()
    proc(filename)


if __name__ == '__main__':
    madmom_get_note_map(filename)

```

### Information about installed software

```
python 3.11 (using anaconda)
madmom 0.16.1
numpy 1.24.3
scipy 1.11.1
cython 3.0.8
mido 1.3.2
packaging 23.1
```

**Comment by lucala** [comment]
I had the same issue. The problem is with the python version we're using. As mentioned in [this stackoverflow post](https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections) the `MutableSequence` is now in `collections.abc`.

Changing line 23 in your `D:\anaconda3\Lib\site-packages\madmom\processors.py` file to `from collections.abc import MutableSequence` solves the issue.

**Comment by codeknowhow** [comment]
If you're on a mac the path is:

~/anaconda3/lib/python3.11/site-packages/madmom/processors.py

Just add the same change that @lucala

**Comment by mgazier** [comment]
i had issues with Madmom + python 3.11 and a few items like collections. i added some code to fix a few settings without having to touch the source code.
https://github.com/mgazier/madmom_python311

**Comment by Centauria** [comment]
It is a python version issue.
madmom will trigger this error when working on Python version >= 3.10
hope for fixing

**Comment by nikhilsos** [comment]
from collections import MutableSequence needs to be changed to
 from collections.abc import MutableSequence

**Comment by josharagon** [comment]
> from collections import MutableSequence needs to be changed to from collections.abc import MutableSequence

thanks mate
